services:
  postgres:
    container_name: postgres
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=cloud_share_db
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data
    
  maildev:
    container_name: maildev
    image: maildev/maildev
    ports:
      - 1025:1025
      - 1080:1080
    restart: always

volumes:
  pg_data: {}